name: ci 

on:
  push:
    branches: 
      - github-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: 'x64'
      - run: |
          cd mkdocs
          python3 -m pip install --upgrade pip \
          pip install requests \
             mkdocs \
             mkdocs-material \
             mkdocs-github-contributors-plugin \
             mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force
